apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stock-intel-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: stock-intel-dev
    app.kubernetes.io/part-of: stock-intelligence
    environment: development
spec:
  project: default
  source:
    repoURL: 'https://github.com/TuanStark/Stock-Intelligence-Saas.git'
    targetRevision: main
    path: gitops/chart
    helm:
      valueFiles:
        - ../envs/dev/values.yaml
  destination:
    name: k3s-production
    namespace: stock-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
